### ISSUE TITLE
Fleet configuration variables -- what is their purpose?

### ISSUE THREAD

**Issue by drjasonharrison-vp-eio** [balena-io-playground/balena-cam#31]
What is the purpose of defining these variables in the fleet configuration?
BALENA_HOST_CONFIG_start_x = 1
BALENA_HOST_CONFIG_gpu_mem_256 = 192
BALENA_HOST_CONFIG_gpu_mem_512 = 256
BALENA_HOST_CONFIG_gpu_mem_1024 = 448

Do they affect the HostOS, or all of the containers?
Perhaps a link to https://www.balena.io/docs/learn/develop/hardware/i2c-and-spi/#raspberry-pi-camera-module

would be helpful

**Comment by mbalamat** [comment]
@drjasonharrison-vp-eio If I get your question right on why we add these variables in the fleet configuration tab is because on [balena-cloud](https://dashboard.balena-cloud.com/) I have an app called balenaCam and if I want to add more devices on this app (essentially more balenaCams) I don't want to set up these variables for every new device that I add, so the reason is convenience, of course you can set them per device but it's more convenient using fleet wide variables. Regarding your second question it's the way to access the hardware of the device as you correctly pointed to the docs.
