### ISSUE TITLE
Ideas!!

### ISSUE THREAD

**Issue by shams3049** [balena-io-playground/balena-cam#44]
any ideas for adding timestamp on the stream gsstreamer?

**Comment by mbalamat** [comment]
@shams3049 it would be a nice addition, you can check the CameraDevice class on server.py and add the timestamp or date on the frame just before returning it. Also if you'd like to discuss more in depth I'd be better to do that on our [forums](https://forums.balena.io) and ping me `@mbalamat`, because this area is for issue tracking.
